version: "3.7"
services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
      - "3000:3000"
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - redis
      - postgres

  redis:
    container_name: redis
    image: "redis:alpine"
    networks:
      - webnet

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - webnet

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - docker.env

networks:
  webnet:

volumes:
  postgres:
  pgadmin:
