version: "3.9"
services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
      - media.env
    ports:
      - "${PORT}:${PORT}"
      - "9229:9229"
    networks:
      - webnet
    depends_on:
      - redis
      - postgres

  redis:
    container_name: redis
    image: "redis:alpine"
    networks:
      - webnet

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - webnet

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    restart: always
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - docker.env
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  postgres:
  pgadmin:
