version: "3"
services:
#  video-video-chat-server:
#    container_name: video-video-chat-server
#    build:
#      dockerfile: Dockerfile
#      context: ../../
#    env_file:
#      - ../../.env
#    volumes:
#      - /app/node_modules
#    ports:
#      - 3000:3000
#      - 9229:9229
#    command: yarn start:dev
#    depends_on:
#      - postgres

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
